# Generated by Django 2.2.3 on 2019-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190713_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hint',
            new_name='nickname',
        ),
    ]
