# Generated by Django 2.2.3 on 2019-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190713_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='hint',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
