# Generated by Django 2.2.3 on 2019-07-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190713_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hint',
            new_name='nickname',
        ),
    ]
