# Generated by Django 2.2.3 on 2019-07-14 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
